/// <reference path="../core/index.d.ts" />
/// <reference path="../extends/index.d.ts" />
/// <reference path="./mongoose.d.ts" />
/// <reference path="../company/cars.d.ts" />
/// <reference path="../settings/settings.d.ts" />
/// <reference path="../company/deals.d.ts" />
/// <reference path="../company/company.d.ts" />
/// <reference path="../company/statusdeals.d.ts" />
/// <reference path="../company/clients.d.ts" />
/// <reference path="../profiles/personal.d.ts" />
/// <reference path="../profiles/profiles.d.ts" />
/// <reference path="../company/news.d.ts" />
/// <reference types="node" />
declare module 'crm-core' {}
