/// <reference types="types/extend" />
/// <reference types="types/mongoose" />
/// <reference types="types/cars" />
/// <reference types="types/settings" />
/// <reference types="types/deals" />
/// <reference types="types/statusdeals" />
/// <reference types="types/company" />
/// <reference types="types/clients" />
/// <reference types="types/personal" />
/// <reference types="types/profiles" />
declare module 'crm-core' {}
